### ISSUE TITLE
Hidden scores factor into average score calculation

### ISSUE THREAD

**Issue by Stef-Verzelen** [thronebutt/thronebutt-bugs#36]
If a score is hidden, or auto-hidden if a banned player did a run, the run still gets factored in with the "average score" calculation up top. Which results in silly stuff like "Average score: 173233". I assume it also gets factored in with "Entries".

**Comment by crescentrose** [comment]
It should get factored in the "entries" (as it is still visible, but crossed over in the list), but won't count in the averages anymore.
